# Generated by Django 5.2.7 on 2025-10-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcompany')),
            ],
        ),
    ]
